# Site settings
title: DVHacks
subtitle: Wello. Me weoe mewoe woeo.
email: hacks@dvcoders.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/dvhacks" # the subpath of your site, e.g. /blog/
url: "http://jakeloo.me" # the base hostname & protocol for your site
twitter_username: jake__loo
github_username:  zjakeloo

# Build settings
markdown: kramdown
